// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsC7Nqj7nhqM54f5ev6jHVfvOIoukGB1g',
    appId: '1:792408269293:android:53ff40dc3a84f8263407e4',
    messagingSenderId: '792408269293',
    projectId: 'onofflab-tamagochi',
    databaseURL: 'https://onofflab-tamagochi-default-rtdb.firebaseio.com',
    storageBucket: 'onofflab-tamagochi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVSbMz0gyIBHtSRYSMTGScXCWfKx1POaI',
    appId: '1:792408269293:ios:3ae4e989927f25f83407e4',
    messagingSenderId: '792408269293',
    projectId: 'onofflab-tamagochi',
    databaseURL: 'https://onofflab-tamagochi-default-rtdb.firebaseio.com',
    storageBucket: 'onofflab-tamagochi.firebasestorage.app',
    iosBundleId: 'com.example.onofflabTamagochiFlutter',
  );
}
